
name: Zillion Builder Pro
on:
  repository_dispatch:
    types: [new_task]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Flet & Build Tools
        run: |
          pip install flet
          flet sdk install
          
      - name: Create main.py
        run: |
          echo "${{ github.event.client_payload.code }}" > main.py

      - name: Build APK
        run: |
          flet build apk main.py

      - name: Upload APK Result
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: build/apk/*.apk
