
name: Zillion Final Fix
on:
  repository_dispatch:
    types: [new_task]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev
          pip install flet
          
      - name: Accept Android Licenses
        run: |
          # هاد السطر كيقبل كاع الرخص أوتوماتيكياً
          yes | flet sdk install
          
      - name: Create main.py
        run: echo "${{ github.event.client_payload.code }}" > main.py

      - name: Build APK
        run: |
          # زيادة --verbose باش نشوفو التفاصيل إيلا طاح خطأ
          flet build apk main.py --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: build/apk/*.apk
